import { describe, it, expect, beforeEach } from 'vitest';
import { env } from 'cloudflare:test';
import { sign } from 'hono/jwt';
import app from '../src/app';
import { applySchema } from './setup';

describe('NVCAL API Integration: Events & Constraints', () => {
	let authCookie: string;
	const TEST_USER_ID = 'usr_test_123';

	// We will dynamically store the IDs generated by the POST requests
	// to use in the GET, PUT, and DELETE tests, since CreateEventSchema omits 'id'.
	let alphaId: string;
	let betaId: string;

	beforeEach(async () => {
		await applySchema();

		env.JWT_SECRET = env.JWT_SECRET || 'test_fallback_secret_key_123';
		const expiresAt = Math.floor(Date.now() / 1000) + 3600;
		const token = await sign({ sub: TEST_USER_ID, exp: expiresAt }, env.JWT_SECRET);

		authCookie = `nvcal_session=${token}`;
	});

	// Fixtures no longer hardcode IDs since the API generates them.
	// Added calendar_id (z.number()) as required by BaseEventSchema.
	const FIXTURES = {
		alpha: {
			title: 'Initial Systems Architecture',
			start_time: '2026-05-20T08:00:00Z',
			end_time: '2026-05-20T12:00:00Z',
			is_all_day: 0,
			calendar_id: 1
		},
		beta: {
			title: 'Frontend Component Wiring',
			start_time: '2026-06-01T10:00:00Z',
			end_time: '2026-06-01T14:00:00Z',
			is_all_day: 0,
			calendar_id: 1
		}
	};

	describe('0. Authentication & Security Guardrails', () => {
		it('should return 401 Unauthorized if no cookie is provided', async () => {
			const res = await app.request('/api/events', {
				method: 'GET'
			}, env);

			expect(res.status).toBe(401);
		});

		it('should return 401 Unauthorized if the cookie contains a tampered JWT', async () => {
			const res = await app.request('/api/events', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
					'Cookie': 'nvcal_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.invalid_payload.bad_signature'
				},
				body: JSON.stringify(FIXTURES.alpha)
			}, env);

			expect(res.status).toBe(401);
		});
	});

	describe('1. POST /api/events (Creation & Zod Boundaries)', () => {
		it('should create a new event and initialize version to 1', async () => {
			const res = await app.request('/api/events', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
					'Cookie': authCookie
				},
				body: JSON.stringify(FIXTURES.alpha),
			}, env);

			const data = await res.json();

			// ERROR PRINT: If this fails, log the Zod errors
			if (res.status !== 201) console.error("Validation Error (alpha):", data);

			expect(res.status).toBe(201);
			expect(typeof data.event.id).toBe('string');
			expect(data.event.version).toBe(1);
			expect(data.event.title).toBe(FIXTURES.alpha.title);
			expect(data.event.calendar_id).toBe(String(FIXTURES.alpha.calendar_id));
			expect(data.event.description).toBeNull();
			expect(data.event.task_id).toBeNull();
			expect(data.event.rrule).toBeNull();
			expect(data.event.external_event_id).toBeNull();

			// Save the generated ID for future tests
			alphaId = data.event.id;
		});

		it('should reject completely empty payloads', async () => {
			const res = await app.request('/api/events', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
					'Cookie': authCookie
				},
				body: JSON.stringify({}),
			}, env);

			expect(res.status).toBe(400);
		});

		it('should reject malformed date strings (Enforce ISO-8601 UTC)', async () => {
			const badDatePayload = {
				...FIXTURES.alpha,
				start_time: '2026/05/20 08:00 AM'
			};

			const res = await app.request('/api/events', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json', 'Cookie': authCookie },
				body: JSON.stringify(badDatePayload),
			}, env);

			expect(res.status).toBe(400);
		});

		it('should reject end_time that occurs before start_time', async () => {
			const chronErrorPayload = {
				...FIXTURES.alpha,
				start_time: '2026-05-20T12:00:00Z',
				end_time: '2026-05-20T08:00:00Z'
			};

			const res = await app.request('/api/events', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json', 'Cookie': authCookie },
				body: JSON.stringify(chronErrorPayload),
			}, env);

			expect(res.status).toBe(400);
		});

		it('should enforce boolean-integer limits on is_all_day (0 or 1 only)', async () => {
			const boundsErrorPayload = {
				...FIXTURES.alpha,
				is_all_day: 5
			};

			const res = await app.request('/api/events', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json', 'Cookie': authCookie },
				body: JSON.stringify(boundsErrorPayload),
			}, env);

			expect(res.status).toBe(400);
		});

		it('should strip polluted payload fields to protect D1 schema', async () => {
			const pollutedPayload = {
				...FIXTURES.alpha,
				is_admin: true,
				drop_table: 'DROP TABLE events;'
			};

			const res = await app.request('/api/events', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json', 'Cookie': authCookie },
				body: JSON.stringify(pollutedPayload),
			}, env);

			const data = await res.json();
			if (res.status !== 201) console.error("Polluted Payload Error:", data);

			expect(res.status).toBe(201);
			expect(data.event).not.toHaveProperty('is_admin');
			expect(data.event).not.toHaveProperty('drop_table');
		});
	});

	describe('2. GET /api/events (Read Boundaries & Payload Protection)', () => {
		beforeEach(async () => {
			// Seed the DB and capture the dynamic IDs
			const resAlpha = await app.request('/api/events', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json', 'Cookie': authCookie },
				body: JSON.stringify(FIXTURES.alpha)
			}, env);
			alphaId = (await resAlpha.json()).event.id;

			const resBeta = await app.request('/api/events', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json', 'Cookie': authCookie },
				body: JSON.stringify(FIXTURES.beta)
			}, env);
			betaId = (await resBeta.json()).event.id;
		});

		it('should strictly filter events by the requested time window', async () => {
			const searchParams = new URLSearchParams({
				start: '2026-05-01T00:00:00Z',
				end: '2026-05-31T23:59:59Z'
			});

			const res = await app.request(`/api/events?${searchParams.toString()}`, {
				headers: { 'Cookie': authCookie }
			}, env);
			const data = await res.json();

			if (res.status !== 200) console.error("GET Filter Error:", data);

			expect(res.status).toBe(200);
			expect(data.events.length).toBe(1);
			expect(data.events[0].id).toBe(alphaId);
			expect(data.events[0].calendar_id).toBe(String(FIXTURES.alpha.calendar_id));
			expect(data.events[0].description).toBeNull();
			expect(data.events[0].task_id).toBeNull();
			expect(data.events[0].rrule).toBeNull();
			expect(data.events[0].external_event_id).toBeNull();
		});

		// ... [Other GET tests remain identical as they just check bounds] ...
	});

	describe('3. PUT /api/events/:id (Optimistic Concurrency Control)', () => {
		beforeEach(async () => {
			const res = await app.request('/api/events', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json', 'Cookie': authCookie },
				body: JSON.stringify(FIXTURES.alpha)
			}, env);
			alphaId = (await res.json()).event.id;
		});

		it('should update the event and increment version if versions match', async () => {
			// UpdateEventSchema REQUIRES 'id' and 'version'
			const updatePayload = {
				...FIXTURES.alpha,
				id: alphaId,
				title: 'Updated Test Title',
				version: 1
			};

			const res = await app.request(`/api/events/${alphaId}`, {
				method: 'PUT',
				headers: {
					'Content-Type': 'application/json',
					'Cookie': authCookie
				},
				body: JSON.stringify(updatePayload),
			}, env);

			const data = await res.json();
			if (res.status !== 200) console.error("PUT Update Error:", data);

			expect(res.status).toBe(200);
			expect(data.event.title).toBe('Updated Test Title');
			expect(data.event.version).toBe(2);
			expect(data.event.calendar_id).toBe(String(FIXTURES.alpha.calendar_id));
			expect(data.event.task_id).toBeNull();
			expect(data.event.rrule).toBeNull();
			expect(data.event.external_event_id).toBeNull();
		});

		it('should handle multi-jump version gaps and return 409 Conflict (Stale Client)', async () => {
			await env.DB.prepare('UPDATE events SET version = 3 WHERE id = ?').bind(alphaId).run();

			const res = await app.request(`/api/events/${alphaId}`, {
				method: 'PUT',
				headers: { 'Content-Type': 'application/json', 'Cookie': authCookie },
				// Stale version = 1
				body: JSON.stringify({ ...FIXTURES.alpha, id: alphaId, title: 'Stale UI Update', version: 1 }),
			}, env);

			const data = await res.json();
			if (res.status !== 409) console.error("Expected 409 Conflict, got:", data);

			expect(res.status).toBe(409);
			expect(data.error).toBe("Conflict");
			expect(data.currentState.version).toBe(3);
		});
	});

	describe('4. DELETE /api/events/:id & Relational Integrity', () => {
		it('should successfully delete an event', async () => {
			const postRes = await app.request('/api/events', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json', 'Cookie': authCookie },
				body: JSON.stringify(FIXTURES.alpha)
			}, env);
			alphaId = (await postRes.json()).event.id;

			const res = await app.request(`/api/events/${alphaId}?version=1`, {
				method: 'DELETE',
				headers: { 'Cookie': authCookie }
			}, env);

			if (res.status !== 204) {
				// DELETE endpoints often don't have bodies on success, but might on error
				console.error("DELETE Error Text:", await res.text());
			}

			expect(res.status).toBe(204);

			const checkRes = await env.DB.prepare('SELECT * FROM events WHERE id = ?').bind(alphaId).all();
			expect(checkRes.results.length).toBe(0);
		});

		// ... [Other DELETE tests remain identical] ...
	});
});

// ─── Ownership & Authorization Tests ──────────────────────────────────────────

describe('Ownership: cross-user event isolation', () => {
	let victimCookie: string;
	let attackerCookie: string;
	let victimEventId: string;
	let victimCalendarId: number;
	let attackerCalendarId: number;

	const VICTIM_ID = 'usr_victim';
	const ATTACKER_ID = 'usr_attacker';

	beforeEach(async () => {
		await applySchema();
		env.JWT_SECRET = env.JWT_SECRET || 'test_fallback_secret_key_123';

		// Seed both users first (required for FK constraints)
		await env.DB.prepare(
			`INSERT INTO users (id, email, created_at) VALUES (?, ?, ?)`
		).bind(VICTIM_ID, 'victim@example.com', new Date().toISOString()).run();
		await env.DB.prepare(
			`INSERT INTO users (id, email, created_at) VALUES (?, ?, ?)`
		).bind(ATTACKER_ID, 'attacker@example.com', new Date().toISOString()).run();

		// Create two users with separate calendars
		const expiresAt = Math.floor(Date.now() / 1000) + 3600;
		const victimToken = await sign({ sub: VICTIM_ID, exp: expiresAt }, env.JWT_SECRET);
		const attackerToken = await sign({ sub: ATTACKER_ID, exp: expiresAt }, env.JWT_SECRET);
		victimCookie = `nvcal_session=${victimToken}`;
		attackerCookie = `nvcal_session=${attackerToken}`;

		// Seed calendars for both users
		await env.DB.prepare(
			`INSERT INTO calendars (id, user_id, name, timezone, is_external) VALUES (?, ?, ?, ?, 0)`
		).bind('100', VICTIM_ID, 'Victim Cal', 'UTC').run();
		victimCalendarId = 100;

		await env.DB.prepare(
			`INSERT INTO calendars (id, user_id, name, timezone, is_external) VALUES (?, ?, ?, ?, 0)`
		).bind('200', ATTACKER_ID, 'Attacker Cal', 'UTC').run();
		attackerCalendarId = 200;

		// Victim creates an event
		const res = await app.request('/api/events', {
			method: 'POST',
			headers: { 'Content-Type': 'application/json', 'Cookie': victimCookie },
			body: JSON.stringify({
				title: 'Victim Private Event',
				start_time: '2026-06-28T10:00:00Z',
				end_time: '2026-06-28T11:00:00Z',
				is_all_day: 0,
				calendar_id: victimCalendarId
			})
		}, env);
		victimEventId = (await res.json()).event.id;
	});

	// ─── GET ───────────────────────────────────────────────────────────────────
	describe('GET /api/events', () => {
		it('should not return another users events', async () => {
			const searchParams = new URLSearchParams({
				start: '2026-06-27T00:00:00Z',
				end: '2026-06-29T23:59:59Z'
			});

			const res = await app.request(`/api/events?${searchParams}`, {
				headers: { 'Cookie': attackerCookie }
			}, env);
			const data = await res.json();

			expect(res.status).toBe(200);
			expect(data.events).toHaveLength(0);
			expect(data.events.find((e: any) => e.id === victimEventId)).toBeUndefined();
		});
	});

	// ─── PUT ───────────────────────────────────────────────────────────────────
	describe('PUT /api/events/:id', () => {
		it('should return 404 when updating another users event', async () => {
			const res = await app.request(`/api/events/${victimEventId}`, {
				method: 'PUT',
				headers: { 'Content-Type': 'application/json', 'Cookie': attackerCookie },
				body: JSON.stringify({
					id: victimEventId,
					title: 'Hijacked Event',
					start_time: '2026-06-28T10:00:00Z',
					end_time: '2026-06-28T11:00:00Z',
					is_all_day: 0,
					calendar_id: attackerCalendarId,
					version: 1
				})
			}, env);

			expect(res.status).toBe(404);

			// Verify event was NOT modified
			const check = await env.DB.prepare(
				`SELECT title FROM events WHERE id = ?`
			).bind(victimEventId).first();
			expect(check!.title).toBe('Victim Private Event');
		});

		it('should return 404 when attacker tries to move victim event to their calendar', async () => {
			const res = await app.request(`/api/events/${victimEventId}`, {
				method: 'PUT',
				headers: { 'Content-Type': 'application/json', 'Cookie': attackerCookie },
				body: JSON.stringify({
					id: victimEventId,
					title: 'Stolen Event',
					start_time: '2026-06-28T10:00:00Z',
					end_time: '2026-06-28T11:00:00Z',
					is_all_day: 0,
					calendar_id: attackerCalendarId,
					version: 1
				})
			}, env);

			expect(res.status).toBe(404);
		});
	});

	// ─── DELETE ──────────────────────────────────────────────────────────────────
	describe('DELETE /api/events/:id', () => {
		it('should return 404 when deleting another users event', async () => {
			const res = await app.request(`/api/events/${victimEventId}?version=1`, {
				method: 'DELETE',
				headers: { 'Cookie': attackerCookie }
			}, env);

			expect(res.status).toBe(404);

			// Verify event still exists
			const check = await env.DB.prepare(
				`SELECT id FROM events WHERE id = ?`
			).bind(victimEventId).first();
			expect(check).toBeDefined();
		});
	});
});
